# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KMoyaRxDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KMoyaRxDemo
  pod 'RxCocoa'
  pod 'Moya/RxSwift', '~> 13.0'
  pod 'HandyJSON'
  pod 'SnapKit', '~> 5.0.0'

  target 'KMoyaRxDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'KMoyaRxDemoUITests' do
    # Pods for testing
  end

end
